# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/php
image: php:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - mysql:latest

variables:
  CUSTOM_BUILD_DIR_ENABLED: 1
  MYSQL_DATABASE: admin_duebus
  MYSQL_ROOT_PASSWORD: admin_duebus
  GIT_CLONE_PATH: "builds/duebus"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - vendor/
    - node_modules/

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - cp .env.testing .env
  # Install Composer and project dependencies.
  - composer install
  
deploy:
  script:
    # Run database migrations.
    - php artisan october:up
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan config:cache

test:
  script:
    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # run frontend tests
    # if you have any task for testing frontend
    # set it in your package.json script
    # comment this out if you don't have a frontend test
    #- npm test
