before_script:
  - echo "Before script"
  - cd /home/admin/domains/denora.ir/duebus #your project path
building:
  stage: build
  script:
    #- git reset --hard
    - git pull origin develop
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan october:up
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan storage:link
    #- sudo chown -R deployer:www-data /var/www/html/{your-project-name}/
    - find /home/admin/domains/denora.ir/duebus -type f -exec chmod 664 {} \;
    - find /home/admin/domains/denora.ir/duebus -type d -exec chmod 775 {} \;
    - chgrp -R www-data storage bootstrap/cache
    - chmod -R ug+rwx storage bootstrap/cache
testing:
  stage: test
  script:
    - php ./vendor/bin/phpunit
deploying:
  stage: deploy
  script:
    - echo "Deployed"
    - php artisan queue:restart #if you use queue