image: php:latest

services:
  - mysql:latest

stages:
  - deploy
  - build
  - composer
  - mirror
  - clean_up

variables:
  CUSTOM_BUILD_DIR_ENABLED: 1
  MYSQL_DATABASE: admin_duebus
  MYSQL_ROOT_PASSWORD: admin_duebus
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_JOB_ID/$CI_PROJECT_NAME'
  DOMAIN_DIR: /home/admin/domains/denora.ir
  BUILD_DIR: $DOMAIN_DIR/build
  SITE_DIR: $DOMAIN_DIR/current/public

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#cache:
#  paths:
#    - vendor/
#    - node_modules/

deploy:
  stage: deploy
  script:
    - cp .env.testing .env
    - mkdir -pv $BUILD_DIR
    - rsync -r --delete ./ $BUILD_DIR
    - sudo chmod -R 755 $BUILD_DIR
    - chmod -R o+w $BUILD_DIR/storage
    - sudo chown -R admin $BUILD_DIR
  only:
    - master

build:
  stage: build
  script:
    - cd $BUILD_DIR
    # Run database migrations.
    - php artisan october:up
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan config:clear
    - php artisan config:cache
  only:
    - master

composer:
  stage: composer
  script:
    - cd $BUILD_DIR
    - composer install
  only:
    - master

mirror:
  stage: mirror
  script:
    - cd $BUILD_DIR
    - php artisan october:mirror public
    - cd public
    - rsync -r --delete ./ $SITE_DIR
  only:
    - master

clean_up:
  stage: clean_up
  script:
    - rm -rf $BUILD_DIR
    - cd /$GIT_CLONE_PATH
    - cd ..
    - rm -rf $CI_PROJECT_NAME
  only:
    - master
